-- Create backgrounds table
CREATE TABLE IF NOT EXISTS backgrounds (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null
);

-- Enable RLS
ALTER TABLE backgrounds ENABLE ROW LEVEL SECURITY;

-- Create policy
CREATE POLICY "Allow all for authenticated users" ON backgrounds
FOR ALL USING (auth.role() = 'authenticated');
